"""
Django settings for local_library project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%y$n46-elq%%nlj(!kv7vm=1!zp3=(*s-78y@jrc=i(*ku!g(5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'UserAuthentication.apps.UserauthenticationConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'formtools',  # provides SessionWizardView used for the registration pipeline
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'local_library.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'local_library.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dsl_project_database',
        'USER': 'trishantsahu',
        'PASSWORD': '920308',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#*********************************************************************************
#
#                   CODE ADDED FOR SENDING MAIL
#
# Testing Email Sending Locally
# To see email logs locally without sending them:

# python
# Copy code
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# This setting is useful for debugging. Replace it with the SMTP backend when deploying to production.
# *********************************************************************************




# EMAIL_BACKEND = 'UserAuthentication.utils.email_backend_with_proxy.ProxySMTPBackend'
# # Proxy settings
# PROXY_HOST = '192.168.2.16'  # Replace with proxy hostname (e.g., 'proxy.example.com')
# PROXY_PORT = 8080          # Replace with proxy port (e.g., 8080)
# PROXY_USERNAME = 'trishant'  # Replace with proxy username
# PROXY_PASSWORD = ''  # Replace with proxy password

# EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
# DEFAULT_FROM_EMAIL = 'harry.jai.potter@gmail.com'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' #for local checking of email facility
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True  # Use TLS for secure connection
# EMAIL_USE_SSL = False  # Do not use SSL if TLS is enabled
# EMAIL_HOST_USER = 'harry.jai.potter@gmail.com'  # Your Gmail address
# EMAIL_HOST_PASSWORD = 'sjss fpuy mdre dxjg'  # Your Gmail password or App Password



AUTH_USER_MODEL = 'UserAuthentication.CustomUser'

# Custom authentication backend that allows login via username, email, OR
# employee_id (see UserAuthentication/backends.py). ModelBackend is kept as
# a fallback so Django's default username-based auth (e.g. createsuperuser,
# admin login) keeps working unchanged.
AUTHENTICATION_BACKENDS = [
    'UserAuthentication.backends.MultiFieldAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Used as the "From" address for all outgoing mail (OTP, account-created,
# password-reset, feedback notifications) instead of hardcoding the address
# in every view.
DEFAULT_FROM_EMAIL = 'trishant@barc.gov.in'

# Wizard-stored OTPs should not outlive a normal registration session.
# This intentionally matches the same 7-minute OTP expiry window that was
# previously implemented by hand in the old register/otp views.
OTP_EXPIRY_MINUTES = 7
