# Generated by Django 5.1.3 on 2024-12-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
